backend:
  name: git-gateway
  repo: mdl95r/test-cms-netlify
  branch: main

media_folder: 'static/images/uploads' # Folder where user uploaded files should go
public_folder: '/images/uploads'

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: sections
    label: Секции сайта
    files:
      - file: data/sections/sections.yml
        label: Секции
        name: sections
        fields:
          - label: Секция
            name: section
            widget: list
            fields:
              - { label: 'Название секции', name: 'title', widget: 'string', required: true}
              - { label: 'Текст', name: 'text', widget: 'markdown'}
              - { label: 'Добавить html', name: 'html', widget: 'relation', collection: code, searchFields: ["name", "code"], displayFields: ["name", code"],  valueField: "name"}
              - { label: 'Скрыть/Показать секцию', name: 'hide', widget: 'boolean', hint: Будет ли отображаться секция на сайте}
  - name: banners
    label: Баннеры
    files:
      - file: data/hero/hero.yml
        label: Баннеры
        name: banners
        fields:
          - label: Баннер
            name: banner
            widget: list
            fields:
              - {label: Изображение, name: img, widget: image, required: true, hint: выбрать изображение}
              - {label: Описание изображения, name: alt, widget: string}
  - name: settings
    label: Общие настройки
    files:
      - file: data/settings/navigation.yml
        label: Навигация
        name: navigation
        fields:
          - label: Меню верхнее
            name: nav_items
            widget: list
            fields:
              - {label: Название, name: label, widget: string, required: true}
              - {label: Путь, name: path, widget: string, hint: По умолчанию путь "#"}
      - file: data/settings/seo.yml
        label: SEO настройки
        name: seo
        fields:
          - {label: Название сайта (title), name: title, widget: string, required: true}
          - {label: Описание сайта (Description), name: description, widget: string, required: true}
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Главная страница"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}

