backend:
  name: git-gateway
  repo: mdl95r/test-cms-netlify
  branch: main

media_folder: 'static/images/uploads' # Folder where user uploaded files should go
public_folder: '/images/uploads'

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: sections
    label: Секции сайта
    files:
      - file: data/sections/sections.yml
        label: Секции
        name: sections
        fields:
          - label: Секция
            name: section
            widget: list
            fields:
              - { label: 'Название секции', name: 'title', widget: 'string', required: true}
              - { label: 'Текст', name: 'text', widget: 'markdown'}
              - { label: 'Добавить html', name: 'html', widget: 'relation', collection: code, searchFields: ["code"], displayFields: ["code"],  valueField: ""}
              - { label: 'Скрыть/Показать секцию', name: 'hide', widget: 'boolean', hint: Будет ли отображаться секция на сайте}
  - name: banners
    label: Баннеры
    files:
      - file: data/hero/hero.yml
        label: Баннеры
        name: banners
        fields:
          - label: Баннер
            name: banner
            widget: list
            fields:
              - {label: Изображение, name: img, widget: image, required: true, hint: выбрать изображение}
              - {label: Описание изображения, name: alt, widget: string}
  - name: settings
    label: Общие настройки
    files:
      - file: data/settings/navigation.yml
        label: Навигация
        name: navigation
        fields:
          - label: Меню верхнее
            name: nav_items
            widget: list
            fields:
              - {label: Название, name: label, widget: string, required: true}
              - {label: Путь, name: path, widget: string, hint: По умолчанию путь "#"}
      - file: data/settings/seo.yml
        label: SEO настройки
        name: seo
        fields:
          - {label: Название сайта (title), name: title, widget: string, required: true}
          - {label: Описание сайта (Description), name: description, widget: string, required: true}
  - name: links
    label: Ссылки
    files:
      - file: data/links/links.yml
        label: Ссылки
        name: links
        fields:
          - label: Ссылка
            name: links
            widget: list
            fields:
              - {label: Название, name: title, widget: string, required: true}
              - {label: Ссылка, name: link, widget: string, required: true}
  - name: code
    label: html блок
    widget: "hidden"
    files:
      - file: data/html/html.yml
        label: html блок
        name: code
        fields:
          - {label: html код, name: code, widget: code, required: true}

