backend:
  name: git-gateway
  repo: mdl95r/test-cms-netlify
  branch: main

media_folder: 'static/images/uploads' # Folder where user uploaded files should go
public_folder: '/images/uploads'

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: sections
    label: Секции сайта
    files:
      - file: data/sections/sections.yml
        label: Секции
        name: sections
        fields:
          - label: Секция
            name: section
            widget: list
            fields:
              - { label: 'Название секции', name: 'title', widget: 'string' }
              - { label: 'Текст', name: 'text', widget: 'markdown' }
  - name: banners
    label: Баннеры
    files:
      - file: data/hero/hero.yml
        label: Баннеры
        name: banners
        fields:
          - label: Баннер
            name: banner
            widget: list
            fields:
              - {label: Изображение, name: img, widget: image}
              - {label: Описание изображения, name: alt, widget: string}
  - name: settings
    label: Общие настройки
    files:
      - file: data/settings/navigation.yml
        label: Навигация
        name: navigation
        fields:
          - label: Меню верхнее
            name: nav_items
            widget: list
            fields:
              - {label: Название, name: label, widget: string}
              - {label: Путь, name: path, widget: string}
      - file: data/settings/seo.yml
        label: SEO настройки
        name: seo
        fields:
          - {label: Название сайта (title), name: title, widget: string}
          - {label: Описание сайта (Description), name: description, widget: string}
  # - name: html
  #   label: HTML блок
  #   files:
  #     - file: data/hero/hero.yml
  #       label: Баннеры
  #       name: banners
  #       fields:
  #         - label: Баннер
  #           name: banner
  #           widget: list
  #           fields:
  #             - {label: Изображение, name: img, widget: image}
  #             - {label: Описание изображения, name: alt, widget: string}

