backend:
  name: git-gateway
  repo: mdl95r/test-cms-netlify
  branch: main

media_folder: 'static/images/uploads' # Folder where user uploaded files should go
public_folder: '/images/uploads'

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: banners
    label: Баннеры
    files:
      - file: data/hero/hero.yml
        label: Баннеры
        name: banners
        fields:
          - label: Баннер
            name: banner
            widget: list
            fields:
              - {label: Изображение, name: img, widget: image, required: true, hint: выбрать изображение}
              - {label: Описание изображения, name: alt, widget: string}
  - name: settings
    label: Общие настройки
    files:
      - file: data/settings/navigation.yml
        label: Навигация
        name: navigation
        fields:
          - label: Меню верхнее
            name: nav_items
            widget: list
            fields:
              - {label: Название, name: label, widget: string, required: true}
              - {label: Путь, name: path, widget: string, hint: По умолчанию путь "#"}
      - file: data/settings/seo.yml
        label: SEO настройки
        name: seo
        fields:
          - {label: Название сайта (title), name: title, widget: string, required: true}
          - {label: Описание сайта (Description), name: description, widget: string, required: true}
  - name: "pages"
    label: "Главная страница"
    files:
      - file: "content/_index.md"
        label: "Главная страница"
        name: "home"
        fields:
          - {label: Название сайта (h1), name: title, widget: string}
          - {label: Лого мода, name: image, widget: image}
          - {label: "Секция о проекте", name: project, widget: object, fields: [
              {label: "Название", name: "heading", widget: string},
              {label: "Текст", name: "text", widget: "markdown"}]}
          - {label: "Секция о нас", name: aboutus, widget: object, fields: [
              {label: "Название", name: "heading", widget: string},
              {label: "Текст", name: "text", widget: "markdown"},
              {label: "Ссылки", name: "links", widget: "list", fields: [
              {label: "Название", name: "title", widget: "string"},
              {label: "Ссылка", name: "link", widget: "string"}]}]}
          - {label: "Секция медиа", name: media, widget: list, max: 6, fields: [
              {label: "Картинка", name: "img", widget: "image"}]}

